AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This stack uses a previously setup Cloudformation macro.
Resources:
  Bucket:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      MasterUsername: dan
      MasterUserPassword:
        'Fn::Transform':
        - Name: PasswordGenerator
          Parameters:
            Length: 20
            Key: /rds/passwords/dan

